services:

  or_app:
    build:
      context: .
    container_name: or_app
    depends_on:
      - odb
    ports:
      - "8086:8082"
    networks:
      - ord-net


  odb:
    image: postgres:16
    container_name: odb
    environment:
      POSTGRES_USER: ${DB_LOGIN}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ordersDB
    networks:
      - ord-net

networks:
  ord-net:
    driver: bridge


volumes:
  db_data: {}