server.port = 8082

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_LOGIN}
spring.datasource.password=${DB_PASSWORD}

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

resilience4j.circuitbreaker.instances.inventoryService.failureRateThreshold= 50
resilience4j.circuitbreaker.instances.inventoryService.waitDurationInOpenState= 10s
resilience4j.circuitbreaker.instances.inventoryService.minimumNumberOfCalls= 5
resilience4j.circuitbreaker.instances.inventoryService.slidingWindowSize= 10

management.endpoints.web.exposure.include = resilience4j.circuitbreakers